// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIKey struct {
	ID            string     `json:"id"`
	GatewayID     string     `json:"gatewayId"`
	PrincipalID   string     `json:"principalId"`
	OrgUnitID     *string    `json:"orgUnitId,omitempty"`
	KeyPrefix     string     `json:"keyPrefix"`
	KeyName       string     `json:"keyName"`
	BudgetID      *string    `json:"budgetId,omitempty"`
	AllowedModels []string   `json:"allowedModels"`
	AllowedIps    []string   `json:"allowedIps"`
	Scopes        []string   `json:"scopes"`
	ExpiresAt     *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt    *time.Time `json:"lastUsedAt,omitempty"`
	TotalSpend    float64    `json:"totalSpend"`
	Blocked       bool       `json:"blocked"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	Gateway       *Gateway   `json:"gateway"`
	Principal     *Principal `json:"principal"`
	OrgUnit       *OrgUnit   `json:"orgUnit,omitempty"`
	Budget        *Budget    `json:"budget,omitempty"`
}

type APIKeyCreationResult struct {
	APIKey *APIKey `json:"apiKey"`
	RawKey string  `json:"rawKey"`
}

type APIKeyFilter struct {
	PrincipalID *string `json:"principalId,omitempty"`
	OrgUnitID   *string `json:"orgUnitId,omitempty"`
	Blocked     *bool   `json:"blocked,omitempty"`
}

type AddGatewayMemberInput struct {
	GatewayID string            `json:"gatewayId"`
	UserID    string            `json:"userId"`
	Role      GatewayMemberRole `json:"role"`
}

type Budget struct {
	ID             string         `json:"id"`
	GatewayID      string         `json:"gatewayId"`
	Name           string         `json:"name"`
	MaxBudget      *float64       `json:"maxBudget,omitempty"`
	BudgetDuration BudgetDuration `json:"budgetDuration"`
	TpmLimit       *int           `json:"tpmLimit,omitempty"`
	RpmLimit       *int           `json:"rpmLimit,omitempty"`
	SoftLimit      *float64       `json:"softLimit,omitempty"`
	Metadata       map[string]any `json:"metadata,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	Gateway        *Gateway       `json:"gateway"`
}

type CreateAPIKeyInput struct {
	GatewayID     string     `json:"gatewayId"`
	PrincipalID   string     `json:"principalId"`
	OrgUnitID     *string    `json:"orgUnitId,omitempty"`
	KeyName       string     `json:"keyName"`
	BudgetID      *string    `json:"budgetId,omitempty"`
	AllowedModels []string   `json:"allowedModels,omitempty"`
	AllowedIps    []string   `json:"allowedIps,omitempty"`
	Scopes        []string   `json:"scopes,omitempty"`
	ExpiresAt     *time.Time `json:"expiresAt,omitempty"`
}

type CreateBudgetInput struct {
	Name           string         `json:"name"`
	MaxBudget      *float64       `json:"maxBudget,omitempty"`
	BudgetDuration BudgetDuration `json:"budgetDuration"`
	TpmLimit       *int           `json:"tpmLimit,omitempty"`
	RpmLimit       *int           `json:"rpmLimit,omitempty"`
	SoftLimit      *float64       `json:"softLimit,omitempty"`
	Metadata       map[string]any `json:"metadata,omitempty"`
}

type CreateGatewayInput struct {
	Alias           string         `json:"alias"`
	ProviderEnabled *bool          `json:"providerEnabled,omitempty"`
	ConsumerEnabled *bool          `json:"consumerEnabled,omitempty"`
	Metadata        map[string]any `json:"metadata,omitempty"`
}

type CreateOrgMembershipInput struct {
	PrincipalID string        `json:"principalId"`
	OrgUnitID   string        `json:"orgUnitId"`
	Role        OrgMemberRole `json:"role"`
	BudgetID    *string       `json:"budgetId,omitempty"`
	IsPrimary   *bool         `json:"isPrimary,omitempty"`
}

type CreateOrgUnitInput struct {
	GatewayID     string         `json:"gatewayId"`
	ParentID      *string        `json:"parentId,omitempty"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	UnitType      OrgUnitType    `json:"unitType"`
	BudgetID      *string        `json:"budgetId,omitempty"`
	AllowedModels []string       `json:"allowedModels,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

type CreatePrincipalInput struct {
	GatewayID       string         `json:"gatewayId"`
	PrincipalType   PrincipalType  `json:"principalType"`
	UserID          *string        `json:"userId,omitempty"`
	ServiceName     *string        `json:"serviceName,omitempty"`
	EnvironmentName *string        `json:"environmentName,omitempty"`
	DisplayName     string         `json:"displayName"`
	BudgetID        *string        `json:"budgetId,omitempty"`
	AllowedModels   []string       `json:"allowedModels,omitempty"`
	Metadata        map[string]any `json:"metadata,omitempty"`
}

type CreateUserInput struct {
	Email        string         `json:"email"`
	Role         UserRole       `json:"role"`
	DisplayName  string         `json:"displayName"`
	AvatarURL    *string        `json:"avatarUrl,omitempty"`
	AuthProvider *string        `json:"authProvider,omitempty"`
	ExternalID   *string        `json:"externalId,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
}

type Gateway struct {
	ID              string               `json:"id"`
	Alias           string               `json:"alias"`
	OwnerUserID     string               `json:"ownerUserId"`
	ProviderEnabled bool                 `json:"providerEnabled"`
	ConsumerEnabled bool                 `json:"consumerEnabled"`
	Metadata        map[string]any       `json:"metadata,omitempty"`
	CreatedAt       time.Time            `json:"createdAt"`
	UpdatedAt       time.Time            `json:"updatedAt"`
	Owner           *User                `json:"owner"`
	Members         []*GatewayMembership `json:"members"`
	OrgUnits        []*OrgUnit           `json:"orgUnits"`
	Principals      []*Principal         `json:"principals"`
	Budgets         []*Budget            `json:"budgets"`
}

type GatewayMembership struct {
	ID        string            `json:"id"`
	UserID    string            `json:"userId"`
	GatewayID string            `json:"gatewayId"`
	Role      GatewayMemberRole `json:"role"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
	User      *User             `json:"user"`
	Gateway   *Gateway          `json:"gateway"`
}

type Mutation struct {
}

type OrgMembership struct {
	ID          string        `json:"id"`
	PrincipalID string        `json:"principalId"`
	OrgUnitID   string        `json:"orgUnitId"`
	Role        OrgMemberRole `json:"role"`
	BudgetID    *string       `json:"budgetId,omitempty"`
	IsPrimary   bool          `json:"isPrimary"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	Principal   *Principal    `json:"principal"`
	OrgUnit     *OrgUnit      `json:"orgUnit"`
	Budget      *Budget       `json:"budget,omitempty"`
}

type OrgUnit struct {
	ID            string           `json:"id"`
	GatewayID     string           `json:"gatewayId"`
	ParentID      *string          `json:"parentId,omitempty"`
	Path          string           `json:"path"`
	Depth         int              `json:"depth"`
	Name          string           `json:"name"`
	Slug          string           `json:"slug"`
	UnitType      OrgUnitType      `json:"unitType"`
	BudgetID      *string          `json:"budgetId,omitempty"`
	AllowedModels []string         `json:"allowedModels"`
	Metadata      map[string]any   `json:"metadata,omitempty"`
	CreatedAt     time.Time        `json:"createdAt"`
	UpdatedAt     time.Time        `json:"updatedAt"`
	Gateway       *Gateway         `json:"gateway"`
	Parent        *OrgUnit         `json:"parent,omitempty"`
	Children      []*OrgUnit       `json:"children"`
	Budget        *Budget          `json:"budget,omitempty"`
	Members       []*OrgMembership `json:"members"`
}

type Principal struct {
	ID              string           `json:"id"`
	GatewayID       string           `json:"gatewayId"`
	PrincipalType   PrincipalType    `json:"principalType"`
	UserID          *string          `json:"userId,omitempty"`
	ServiceName     *string          `json:"serviceName,omitempty"`
	EnvironmentName *string          `json:"environmentName,omitempty"`
	DisplayName     string           `json:"displayName"`
	BudgetID        *string          `json:"budgetId,omitempty"`
	AllowedModels   []string         `json:"allowedModels"`
	Metadata        map[string]any   `json:"metadata,omitempty"`
	CreatedAt       time.Time        `json:"createdAt"`
	UpdatedAt       time.Time        `json:"updatedAt"`
	Gateway         *Gateway         `json:"gateway"`
	User            *User            `json:"user,omitempty"`
	Budget          *Budget          `json:"budget,omitempty"`
	Memberships     []*OrgMembership `json:"memberships"`
	APIKeys         []*APIKey        `json:"apiKeys"`
}

type PrincipalFilter struct {
	Type      *PrincipalType `json:"type,omitempty"`
	OrgUnitID *string        `json:"orgUnitId,omitempty"`
	Search    *string        `json:"search,omitempty"`
}

type Query struct {
}

type UpdateAPIKeyInput struct {
	KeyName       *string    `json:"keyName,omitempty"`
	BudgetID      *string    `json:"budgetId,omitempty"`
	AllowedModels []string   `json:"allowedModels,omitempty"`
	AllowedIps    []string   `json:"allowedIps,omitempty"`
	ExpiresAt     *time.Time `json:"expiresAt,omitempty"`
	Blocked       *bool      `json:"blocked,omitempty"`
}

type UpdateBudgetInput struct {
	Name           *string         `json:"name,omitempty"`
	MaxBudget      *float64        `json:"maxBudget,omitempty"`
	BudgetDuration *BudgetDuration `json:"budgetDuration,omitempty"`
	TpmLimit       *int            `json:"tpmLimit,omitempty"`
	RpmLimit       *int            `json:"rpmLimit,omitempty"`
	SoftLimit      *float64        `json:"softLimit,omitempty"`
	Metadata       map[string]any  `json:"metadata,omitempty"`
}

type UpdateGatewayInput struct {
	Alias           *string        `json:"alias,omitempty"`
	ProviderEnabled *bool          `json:"providerEnabled,omitempty"`
	ConsumerEnabled *bool          `json:"consumerEnabled,omitempty"`
	Metadata        map[string]any `json:"metadata,omitempty"`
}

type UpdateOrgMembershipInput struct {
	Role      *OrgMemberRole `json:"role,omitempty"`
	BudgetID  *string        `json:"budgetId,omitempty"`
	IsPrimary *bool          `json:"isPrimary,omitempty"`
}

type UpdateOrgUnitInput struct {
	Name          *string        `json:"name,omitempty"`
	Slug          *string        `json:"slug,omitempty"`
	UnitType      *OrgUnitType   `json:"unitType,omitempty"`
	BudgetID      *string        `json:"budgetId,omitempty"`
	AllowedModels []string       `json:"allowedModels,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

type UpdatePrincipalInput struct {
	DisplayName   *string        `json:"displayName,omitempty"`
	BudgetID      *string        `json:"budgetId,omitempty"`
	AllowedModels []string       `json:"allowedModels,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

type UpdateUserInput struct {
	DisplayName *string        `json:"displayName,omitempty"`
	AvatarURL   *string        `json:"avatarUrl,omitempty"`
	Role        *UserRole      `json:"role,omitempty"`
	Status      *UserStatus    `json:"status,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type User struct {
	ID                 string               `json:"id"`
	Email              string               `json:"email"`
	Role               UserRole             `json:"role"`
	DisplayName        string               `json:"displayName"`
	AvatarURL          *string              `json:"avatarUrl,omitempty"`
	Status             UserStatus           `json:"status"`
	AuthProvider       string               `json:"authProvider"`
	ExternalID         *string              `json:"externalId,omitempty"`
	LastLoginAt        *time.Time           `json:"lastLoginAt,omitempty"`
	Metadata           map[string]any       `json:"metadata,omitempty"`
	CreatedAt          time.Time            `json:"createdAt"`
	UpdatedAt          time.Time            `json:"updatedAt"`
	OwnedGateways      []*Gateway           `json:"ownedGateways"`
	GatewayMemberships []*GatewayMembership `json:"gatewayMemberships"`
}

type UserFilter struct {
	Role   *UserRole   `json:"role,omitempty"`
	Status *UserStatus `json:"status,omitempty"`
	Search *string     `json:"search,omitempty"`
}

type BudgetDuration string

const (
	BudgetDurationDaily   BudgetDuration = "DAILY"
	BudgetDurationWeekly  BudgetDuration = "WEEKLY"
	BudgetDurationMonthly BudgetDuration = "MONTHLY"
	BudgetDurationTotal   BudgetDuration = "TOTAL"
)

var AllBudgetDuration = []BudgetDuration{
	BudgetDurationDaily,
	BudgetDurationWeekly,
	BudgetDurationMonthly,
	BudgetDurationTotal,
}

func (e BudgetDuration) IsValid() bool {
	switch e {
	case BudgetDurationDaily, BudgetDurationWeekly, BudgetDurationMonthly, BudgetDurationTotal:
		return true
	}
	return false
}

func (e BudgetDuration) String() string {
	return string(e)
}

func (e *BudgetDuration) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BudgetDuration(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BudgetDuration", str)
	}
	return nil
}

func (e BudgetDuration) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BudgetDuration) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BudgetDuration) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GatewayMemberRole string

const (
	GatewayMemberRoleOwner  GatewayMemberRole = "OWNER"
	GatewayMemberRoleAdmin  GatewayMemberRole = "ADMIN"
	GatewayMemberRoleMember GatewayMemberRole = "MEMBER"
)

var AllGatewayMemberRole = []GatewayMemberRole{
	GatewayMemberRoleOwner,
	GatewayMemberRoleAdmin,
	GatewayMemberRoleMember,
}

func (e GatewayMemberRole) IsValid() bool {
	switch e {
	case GatewayMemberRoleOwner, GatewayMemberRoleAdmin, GatewayMemberRoleMember:
		return true
	}
	return false
}

func (e GatewayMemberRole) String() string {
	return string(e)
}

func (e *GatewayMemberRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GatewayMemberRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GatewayMemberRole", str)
	}
	return nil
}

func (e GatewayMemberRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GatewayMemberRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GatewayMemberRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgMemberRole string

const (
	OrgMemberRoleAdmin  OrgMemberRole = "ADMIN"
	OrgMemberRoleMember OrgMemberRole = "MEMBER"
	OrgMemberRoleViewer OrgMemberRole = "VIEWER"
)

var AllOrgMemberRole = []OrgMemberRole{
	OrgMemberRoleAdmin,
	OrgMemberRoleMember,
	OrgMemberRoleViewer,
}

func (e OrgMemberRole) IsValid() bool {
	switch e {
	case OrgMemberRoleAdmin, OrgMemberRoleMember, OrgMemberRoleViewer:
		return true
	}
	return false
}

func (e OrgMemberRole) String() string {
	return string(e)
}

func (e *OrgMemberRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgMemberRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgMemberRole", str)
	}
	return nil
}

func (e OrgMemberRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgMemberRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgMemberRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgUnitType string

const (
	OrgUnitTypeDepartment OrgUnitType = "DEPARTMENT"
	OrgUnitTypeTeam       OrgUnitType = "TEAM"
	OrgUnitTypeGroup      OrgUnitType = "GROUP"
	OrgUnitTypeProject    OrgUnitType = "PROJECT"
)

var AllOrgUnitType = []OrgUnitType{
	OrgUnitTypeDepartment,
	OrgUnitTypeTeam,
	OrgUnitTypeGroup,
	OrgUnitTypeProject,
}

func (e OrgUnitType) IsValid() bool {
	switch e {
	case OrgUnitTypeDepartment, OrgUnitTypeTeam, OrgUnitTypeGroup, OrgUnitTypeProject:
		return true
	}
	return false
}

func (e OrgUnitType) String() string {
	return string(e)
}

func (e *OrgUnitType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgUnitType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgUnitType", str)
	}
	return nil
}

func (e OrgUnitType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgUnitType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgUnitType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PrincipalType string

const (
	PrincipalTypeUser        PrincipalType = "USER"
	PrincipalTypeService     PrincipalType = "SERVICE"
	PrincipalTypeEnvironment PrincipalType = "ENVIRONMENT"
)

var AllPrincipalType = []PrincipalType{
	PrincipalTypeUser,
	PrincipalTypeService,
	PrincipalTypeEnvironment,
}

func (e PrincipalType) IsValid() bool {
	switch e {
	case PrincipalTypeUser, PrincipalTypeService, PrincipalTypeEnvironment:
		return true
	}
	return false
}

func (e PrincipalType) String() string {
	return string(e)
}

func (e *PrincipalType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PrincipalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PrincipalType", str)
	}
	return nil
}

func (e PrincipalType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PrincipalType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PrincipalType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleRootAdmin UserRole = "ROOT_ADMIN"
	UserRoleAdmin     UserRole = "ADMIN"
	UserRoleUser      UserRole = "USER"
)

var AllUserRole = []UserRole{
	UserRoleRootAdmin,
	UserRoleAdmin,
	UserRoleUser,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleRootAdmin, UserRoleAdmin, UserRoleUser:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
